[package]
name = "urdobot-app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
html-escape = "0.2.13"
lol_html = "1.2.0"
regex = "1.10.2"
reqwest = "0.11.22"
reqwest_cookie_store = "0.6.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
